name: Release
on:
  push:
    branches:
      - main
      - beta
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
  release:
    runs-on: ubuntu-latest
    needs: ['build-and-test']
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Unzip artifact
        run: |
          tar -xf build.tar.gz -C .
          rm -rf build.tar.gz
      - name: Authenticate on NPM
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - name: Release
        run: |
          yarn link
          yarn prepare
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          if [ "${{ github.ref }}" = "refs/heads/beta" ]
          then
            echo "Beta release:"
            yarn release --conventional-prerelease --preid beta --no-changelog
          else
            echo "Main release:"
            yarn release --conventional-graduate --create-release github
          fi
      - name: Publish
        run: npm run publish
